apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: nodeapp
  labels:
    app: nodeapp
    environment: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: dmsubhajit/nodeapp-k8s:latest
        ports:
        - containerPort: 3000
